site_name: "Understand Container"
repo_url: https://github.com/binchenX/understand_container

nav:
  - OCI Specification: "ch1.md"
  - Namespaces: "ch2.md"
  - Cgroups: "ch3.md"
  - Capabilities: "ch4.md"
  - Filesystems: "ch5.md"
  - Root & Users: "ch6.md"
  - Network: "ch7.md"
  - CNI: "ch8.md"

extra_css:
  - assets/custom.css
extra_javascript:
  - assets/inject-link.js

theme:
  name: material
