site_name: "Understand Container"

nav:
  - OCI Specification: "ch1.md"
  - Namespaces: "ch2.md"
  - Cgroups: "ch3.md"
  - Capabilities: "ch4.md"
  - Filesystems: "ch5.md"
  - Root & Users: "ch6.md"
  - Network: "ch7.md"
  - CNI: "ch8.md"
